---
- name: Set Interactive Logon Message Title
  hosts: windows
  gather_facts: false
  tasks:
    - name: Set Interactive logon message title
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticecaption
        data: "Hello Redux"
        type: string

    - name: Set Interactive logon message text
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticetext
        data: "This system is for Redux users only"
        type: string
