---
- name: Set Interactive Logon Message Title
  hosts: windows
  gather_facts: false
  tasks:
    - name: Set Interactive logon message title
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticecaption
        data: "$Heading"
        type: string

    - name: Set Interactive logon message text
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: legalnoticetext
        data: "$discription"
        type: string
  handlers:
    - name: Reboot Windows
      win_reboot:
        reboot_timeout: 600
        msg: "System is restarting after policy update."
